### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by janoliver** [orest-d/p4vasp#2]
The program (already during build process) seems to be only Python 2 compatible. I had to replace `python -c ...` with `python2 -c ...` in `src/Configuration.mk` and `odpdom/Makefile` for successful compilation. 

Either point specifically at python 2 everywhere, or (which is much better) make the code python 3 compatible.

**Comment by orest-d** [comment]
You are right, p4vasp is not python3-compatible. Quite a big rewrite is needed(and tentatively planned) to help with this problem. As for the python binary naming, according to pep 394 (https://www.python.org/dev/peps/pep-0394/), python should point to python 2.
