### ISSUE TITLE
python cannot be found after installing p4vasp

### ISSUE THREAD

**Issue by gvenus** [orest-d/p4vasp#5]
Hi, I installed p4vasp following the README as local user. However, when I set the environmental avails, many command cannot be used, including python, ls, rm, vi. What could I do ?

**Comment by orest-d** [comment]
Most likely something unexpected has happened to .bashrc. (Look at bashrc and setenvironment targets in Makefile.) Check your .bashrc and remove the lines that p4vasp installation has added. Usually it looks like this:
`# set p4vasp environment variables`
`export PATH=$PATH:/...`

Please let me know if you manage to identify the cause of this problem.

**Comment by gvenus** [comment]
@orest-d 
yes, I just deleted the lines related to p4vasp in .bashrc

**Comment by gvenus** [comment]
@orest-d thank you !
