### ISSUE TITLE
cp4vasp Import Error: Undefined Symbol

### ISSUE THREAD

**Issue by iicurtis** [orest-d/p4vasp#7]
After running the install script, which works fine, the `p4v` executable produces the following error:

```
Traceback (most recent call last):
  File "/usr/bin/p4v.py", line 28, in <module>
    from   p4vasp.SystemPM import *
  File "/usr/lib64/python2.7/site-packages/p4vasp/SystemPM.py", line 131, in <module>
    import cp4vasp
  File "/usr/lib64/python2.7/site-packages/cp4vasp.py", line 28, in <module>
    _cp4vasp = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/cp4vasp.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cp4vasp', fp, pathname, description)
ImportError: /usr/lib64/python2.7/site-packages/_cp4vasp.so: undefined symbol: _ZN12Fl_Gl_Window6resizeEiiii
```

I have attempted both local and global install (though didn't expect to see any difference). 

The diagnostic script produces:

```
p4vasp Diagnostics

Python version: 2.7.15 (default, May 15 2018, 15:37:31) 
                [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
Platform:       linux2
Issue:          \S
                Kernel \r on an \m (\l)
Hostname:       cme-mccl437-01.cme.uidaho.edu
LINUX:          Linux 4.16.14-200.fc27.x86_64

Executable:     /usr/bin/python2

Module paths:   /home/icurtis/Downloads/BUILD/p4vasp
                /usr/lib/python27.zip
                /usr/lib64/python2.7
                /usr/lib64/python2.7/plat-linux2
                /usr/lib64/python2.7/lib-tk
                /usr/lib64/python2.7/lib-old
                /usr/lib64/python2.7/lib-dynload
                /usr/lib64/python2.7/site-packages
                /usr/lib64/python2.7/site-packages/gtk-2.0
                /usr/lib/python2.7/site-packages

Enviromental variables:
P4VASP_HOME     not set
PYTHONPATH      not set
PYTHONHOME      not set

Python.h was not found in /usr/include/python/Python.h
FLTK:
  fltk-config:  /usr/bin/fltk-config
  version:      1.3.4
  api-version:  1.3
  libs:         /usr/lib64/libfltk_gl.a
                /usr/lib64/libfltk.a
  c++ flags:    

p4vasp configuration info:
p4vasp_home   = /usr/lib/p4vasp
name          = p4vasp
version       = develop-brance
release       = Null
build_date    = April 28 2018
Can not import _cp4vasp. Have you compiled and installed it ?
(make; make install)


You probably will not be able to compile, since Python.h is missing.
It is expected to be in %s.
Most likely you do not have the python development headders installed.
They are usually located in a package called python-devel (or something like that).
If you have the headders at a non-standart path, you will need to modify
your Makefiles (mainly thesrc/Makefile).


Can not import cp4vasp, however the _cp4vasp can be imported.
I have no clue what is the problem...
Maybe the stack trace will help:

Traceback (most recent call last):
  File "diagnostic.py", line 193, in <module>
    import cp4vasp
  File "/usr/lib64/python2.7/site-packages/cp4vasp.py", line 28, in <module>
    _cp4vasp = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/cp4vasp.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cp4vasp', fp, pathname, description)
ImportError: /usr/lib64/python2.7/site-packages/_cp4vasp.so: undefined symbol: _ZN12Fl_Gl_Window6resizeEiiii
```

`Python.h` is found at `/usr/include/python2.7/`. The system finds it just fine when compiling, so I don't think a symlink will help.

**Comment by iicurtis** [comment]
Maybe this should be in the README.

Everything works now, just needed to specify the correct /lib directory for Fedora's lib64 shenanigans.

For fedora, the correct make commands should be:
```
make P4VASP_HOME=/usr/share/p4vasp \
    PYTHON_HOME=/usr/lib64/python2.7 \
    PYINCLUDE=/usr/include/python2.7

make P4VASP_HOME=/usr/share/p4vasp \
    PYTHON_HOME=/usr/lib64/python2.7 \
    PYINCLUDE=/usr/include/python2.7 \
    SITE_PACKAGES=/usr/lib64/python2.7/site-packages \
    INCLUDEDIR=/usr/include \
    LIBDIR=/usr/lib64 \
    BINDIR=/usr/bin install
```
The issue is the lib64 directory.

**Comment by amorshedi** [comment]
I'm getting this exact same issue on Ubuntu. There is no lib64 there, so I haven't been able to make it work!
Any suggestions would be appreciated.

**Comment by Mohamed-eiss** [comment]
i have the same issue, please are you solve that problem?

**Comment by zhcui** [comment]
same issue here, any suggestion to solve?

**Comment by Chengcheng-Xiao** [comment]
This error is most likely caused by not finding a valid `fltk-config`. 

In `src/fltk-config.py`:
```
if 0 and strip(run("fltk-config --version")) in ["1.1.5","1.1.6","1.1.7","1.1.8"]:
    print run("fltk-config "+" ".join(sys.argv[1:]))
else:
    if not os.path.exists("../ext/bin/fltk-config"):
        os.system("cd ../ext; bash build-fltk.sh >build-fltk.log 2>build-fltk.err")
    print run("../ext/bin/fltk-config "+" ".join(sys.argv[1:]))
```
we see if we don't have `fltk` installed or the installed version is not `["1.1.5","1.1.6","1.1.7","1.1.8"]`, the program will try to compile `fltk` in `ext` folder. But the distro does not have `fltk` tarball in the `ext` folder. Essentially, this tells us that during the compilation of `p4vasp`, no `fltk-config` was used.

To fix this, simply install `fltk` yourself:
```
sudo apt install libfltk1.3-dev
```
 and modify `src/fltk-config.py` to :
```
#!/usr/bin/env python2

import os
import os.path
import sys
from string import *

def run(cmd):
    os.system("%s >fltk-config.tmp"%cmd)
    return open("fltk-config.tmp").read()

print run("fltk-config "+" ".join(sys.argv[1:]))
```

If errors occur in the linking process saying that `ld` cannot find `-lXrender -lXcursor -lxft -lfontconfig`, install these packages:
```
sudo apt install libxrender-dev
sudo apt install libxcursor-dev
sudo apt install libxinerama-dev
```

**Comment by soumyajyotih** [comment]
Thanks Chengcheng-Xiao, this helps.

**Comment by aminul-haque-shawon** [comment]
@Chengcheng-Xiao  Did you reinstall p4vasp after making the edits in src/fltk-config? I tried reinstalling but it did not solve the problem.

**Comment by Chengcheng-Xiao** [comment]
@aminul-haque-shawon Yes, I did reinstall p4vasp after making those changes. Sorry I won't be able to help you with this for it's been almost a year and I have since turned to other open-source packages for postprocessing VASP's outputs ([sumo](https://github.com/SMTG-UCL/sumo) for example).

**Comment by aminul-haque-shawon** [comment]
@Chengcheng-Xiao  Thanks. I tried reinstalling and this time fltk compiled everything correctly. But unfortunately the problem was not solved. I guess there seems to be some problem with the shared object file (_cp4vasp.so) itself and some other linking problems. I tried `ld _cp4vasp` and it returned a lot of '**_undefined reference to x_**' issues.

**Comment by Chengcheng-Xiao** [comment]
@aminul-haque-shawon Alternatively, if you use mac, check out my gist on [how to run p4v using docker](https://gist.github.com/Chengcheng-Xiao/33f32f7719aa32fd29ffa1d16d71c406) (adaptation to linux should be fairly easy though).

**Comment by aminul-haque-shawon** [comment]
So I found a solution to this problem.

After installing (make sure you have all the dependencies met), just compile cp4vasp.py (found in p4vasp/lib)) manually. And that's it!

**Comment by levinit** [comment]
> So I found a solution to this problem.
> 
> 
> 
> After installing (make sure you have all the dependencies met), just compile cp4vasp.py (found in p4vasp/lib)) manually. And that's it!

hi, how to compile cp4vasp.py
python -m py_compile cp4vasp.py    to cover pyc file？
